export const ProductList = [
  {
    id: "1",
    name: "Honor 128/8GB",
    store: "Kontakt Home",
    price: "765AZN",
    oldPrice: "900AZN",
    discount: "20%",
    saving: "135AZN",
    priceCount: "35",
    image: "/images/phone1.avif",
  },
  {
    id: "1",
    name: "Honor 128/8GB",
    store: "Kontakt Home",
    price: "765AZN",
    oldPrice: "900AZN",
    discount: "20%",
    saving: "135AZN",
    priceCount: "35",
    image: "/images/phone2.avif",
  },
  {
    id: "1",
    name: "Honor 128/8GB",
    store: "Kontakt Home",
    price: "765AZN",
    oldPrice: "900AZN",
    discount: "20%",
    saving: "135AZN",
    priceCount: "35",
    image: "/images/phone3.avif",
  },
  {
    id: "1",
    name: "Honor 128/8GB",
    store: "Kontakt Home",
    price: "765AZN",
    oldPrice: "900AZN",
    discount: "20%",
    saving: "135AZN",
    priceCount: "35",
    image: "/images/phone1.avif",
  },
  {
    id: "1",
    name: "Honor 128/8GB",
    store: "Kontakt Home",
    price: "765AZN",
    oldPrice: "900AZN",
    discount: "20%",
    saving: "135AZN",
    priceCount: "35",
    image: "/images/teapot1.avif",
  },
  {
    id: "1",
    name: "Honor 128/8GB",
    store: "Kontakt Home",
    price: "765AZN",
    oldPrice: "900AZN",
    discount: "20%",
    saving: "135AZN",
    priceCount: "35",
    image: "/images/phone2.avif",
  },
  {
    id: "1",
    name: "Honor 128/8GB",
    store: "Kontakt Home",
    price: "765AZN",
    oldPrice: "900AZN",
    discount: "20%",
    saving: "135AZN",
    priceCount: "35",
    image: "/images/phone2.avif",
  },
  {
    id: "1",
    name: "Honor 128/8GB",
    store: "Kontakt Home",
    price: "765AZN",
    oldPrice: "900AZN",
    discount: "20%",
    saving: "135AZN",
    priceCount: "35",
    image: "/images/phone2.avif",
  },
  {
    id: "1",
    name: "Honor 128/8GB",
    store: "Kontakt Home",
    price: "765AZN",
    oldPrice: "900AZN",
    discount: "20%",
    saving: "135AZN",
    priceCount: "35",
    image: "/images/phone2.avif",
  },
  {
    id: "1",
    name: "Honor 128/8GB",
    store: "Kontakt Home",
    price: "765AZN",
    oldPrice: "900AZN",
    discount: "20%",
    saving: "135AZN",
    priceCount: "35",
    image: "/images/phone2.avif",
  },
  {
    id: "1",
    name: "Honor 128/8GB",
    store: "Kontakt Home",
    price: "765AZN",
    oldPrice: "900AZN",
    discount: "20%",
    saving: "135AZN",
    priceCount: "35",
    image: "/images/phone2.avif",
  },
  {
    id: "1",
    name: "Honor 128/8GB",
    store: "Kontakt Home",
    price: "765AZN",
    oldPrice: "900AZN",
    discount: "20%",
    saving: "135AZN",
    priceCount: "35",
    image: "/images/phone2.avif",
  },
  {
    id: "1",
    name: "Honor 128/8GB",
    store: "Kontakt Home",
    price: "765AZN",
    oldPrice: "900AZN",
    discount: "20%",
    saving: "135AZN",
    priceCount: "35",
    image: "/images/phone2.avif",
  },
  {
    id: "1",
    name: "Honor 128/8GB",
    store: "Kontakt Home",
    price: "765AZN",
    oldPrice: "900AZN",
    discount: "20%",
    saving: "135AZN",
    priceCount: "35",
    image: "/images/phone2.avif",
  },
  {
    id: "1",
    name: "Honor 128/8GB",
    store: "Kontakt Home",
    price: "765AZN",
    oldPrice: "900AZN",
    discount: "20%",
    saving: "135AZN",
    priceCount: "35",
    image: "/images/phone2.avif",
  },
];
